---
- name: Install Snap packages
  ansible.builtin.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ snap_packages }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Ensure virtualenv is installed
  ansible.builtin.package:
    name: python3-virtualenv
    state: present

- name: Create a virtual environment for Python packages
  ansible.builtin.command:
    cmd: python3 -m venv /opt/venv
  args:
    creates: /opt/venv

- name: Install pip packages in the virtual environment
  ansible.builtin.command:
    cmd: /opt/venv/bin/pip install "{{ item }}"
  loop: "{{ pip_packages }}"

- name: Link pre-commit to /usr/local/bin
  ansible.builtin.file:
    src: /opt/venv/bin/pre-commit
    dest: /usr/local/bin/pre-commit
    state: link
